### ISSUE TITLE
[EPIC] Allow users to migrate their accounts to HEBorn

### ISSUE THREAD

**Issue by umamaistempo** [HackerExperience/HEBornMigration#1]
## Description
This epic is focused on tasks required to provide a simple webpage where users can request their accounts to be migrated to HEBorn (ie: reserve accounts)

## Tasks
- [x] #2 Store user accounts just like Helix
- [x] #3 Store "account to be reclaimed"

**Comment by chrisfls** [comment]
I think this might be ready :smile:

But I'm just not sure about how to test it on production environment, I know that we'll need a `prod.secret.exs` with the secret keys, but that's everything I know.

I'll open an issue about putting this to run and close this epic.
