### ISSUE TITLE
Store user accounts just like Helix

### ISSUE THREAD

**Issue by umamaistempo** [HackerExperience/HEBornMigration#2]
The produced records must be 1:1 to Helix handles them (except for the ID, the id can be sequential or anything else).

So
1) Same format
2) Same validation rules
3) Same password hashing technique and rules
etc

**Comment by chrisfls** [comment]
Little problem:

> HE2/HEBorn accounts allows usernames with up to 14 characters, HE1 accounts allows up to 15.

I don't think making a renaming processs is worth it (it would allow username stealing) and chopping the last character is also a pretty bad solution, so I'm proposing to change the the validation to allow up to 15 characters.
