### ISSUE TITLE
Release Build

### ISSUE THREAD

**Issue by Devastator67** [HackerExperience/HEBornMigration#46]
When this is released will you have to run Phoenix to run HEBorn in your browser?
As my computer can't run Phoenix I have Windows XP

**Comment by chrisfls** [comment]
No, and this project is not HEBorn, it just handles _HE legacy_ username migration :)

Anyways, I'll try to explain how it works:

1. A player logs on _HE legacy_ and clicks the migrate button
2. This service builds a secret migration url to allow this player to create an HEBorn account with his old _HE legacy_ username
3. The player gets redirected to this secret url and registers a new account HEBorn account, the service registers it using his _HE legacy_ username and sends an confirmation email... then the player confirms the account
4. There's no step four, it's really just that, the migration is done.

Don't worry about hosting things, you won't need to host anything to play.

It may be confusing 'cause it's open source and all, but it's just that we just like to build most of our things open source :smile:

**Comment by Devastator67** [comment]
ok thanks
